~ "resistor-color-trio.ua" ~ ResistorTrio

# Orange and orange and black
⍤⤙≍ "33 ohms"       ResistorTrio {"orange" "orange" "black"}

# Blue and grey and brown
⍤⤙≍ "680 ohms"      ResistorTrio {"blue" "grey" "brown"}

# Red and black and red
⍤⤙≍ "2 kiloohms"    ResistorTrio {"red" "black" "red"}

# Green and brown and orange
⍤⤙≍ "51 kiloohms"   ResistorTrio {"green" "brown" "orange"}

# Yellow and violet and yellow
⍤⤙≍ "470 kiloohms"  ResistorTrio {"yellow" "violet" "yellow"}

# Blue and violet and blue
⍤⤙≍ "67 megaohms"   ResistorTrio {"blue" "violet" "blue"}

# Minimum possible value
⍤⤙≍ "0 ohms"        ResistorTrio {"black" "black" "black"}

# Maximum possible value
⍤⤙≍ "99 gigaohms"   ResistorTrio {"white" "white" "white"}

# First two colors make an invalid octal number
⍤⤙≍ "8 ohms"        ResistorTrio {"black" "grey" "black"}

# Ignore extra colors
⍤⤙≍ "650 kiloohms"  ResistorTrio {"blue" "green" "yellow" "orange"}
