IsPalindrome ← ≍⇌.°⋕
Palindromes  ← ◌◌ ⍢(+1 ⨬(∘|⊃(⊙∘|⊂⊙◌)) ⊸IsPalindrome|≥) ⊙⊙[]
Candidates   ← ⍜(--1)⇡ ∩(×.)

Candidates  ← ⍜(--1)⇡ ∩(×.)
Palindrome  ← ⍜(°⋕|⊂⟜⇌)
Palindromes ← ≡Palindrome Candidates
Factors ← (
  ◡(⋅Candidates)
  ◡÷
  ◡(×⊃(
      ⊙⋅⋅∘
      :
      ≥
    | ⊙⋅⋅⋅∘
      :
      ≤
    ))
  ⊃(▽|▽⊙◌)
  (=⌊.).
  ⊃(▽|▽⊙◌)
  ◴≡(⍆⊂)
)

Largest ← (
  ◡Palindromes
  ⍚Factors

  /◇⊂⊸⍚(>0⧻)
  ▽
  ≡(⊂⊂◡× °⊂)°□⊣
  ⊙⋅⋅⋅ # TODO: fix
)
Smallest ← (
  ◡Palindromes
  ⍚Factors

  /◇⊂⊸⍚(>0⧻)
  ▽
  ≡(⊂⊂◡× °⊂)°□⊢
  ⊙⋅⋅⋅ # TODO: fix
)

Candidates   ← ⍜(--1)⇡ ∩(×.)
IsPalindrome ← ≍⇌.°⋕
Palindromes  ← ▽⊸≡IsPalindrome Candidates

# Palindrome  ← ⍜(°⋕|⊂⟜⇌)
# Palindromes ← ≡Palindrome Candidates
# Factors ← (
# ◡(⋅Candidates)
# ◡÷
# ◡(×⊃(
# ⊙⋅⋅∘
# :
# ≥
# | ⊙⋅⋅⋅∘
# :
# ≤
# ))
# ⊃(▽|▽⊙◌)
# (=⌊.).
# ⊃(▽|▽⊙◌)
# ◴≡(⍆⊂)
# )

# 100 999
# 906609
# Factors

# Candidates 1 9

Palindromes 1000 9999

# IsPalindrome

# ⍚Factors
#
# /◇⊂⊸⍚(>0⧻)
# ▽
# ≡(⊂⊂◡× °⊂)°□⊣
# ⊙⋅⋅⋅ # TODO: fix
#

# https://www.uiua.org/pad?src=0_14_0-dev_7__Q2FuZGlkYXRlcyAgIOKGkCDijZwoLS0xKeKHoSDiiKkow5cuKQpJc1BhbGluZHJvbWUg4oaQIOKJjeKHjC7CsOKLlQpQYWxpbmRyb21lcyAg4oaQIOKWveKKuOKJoUlzUGFsaW5kcm9tZSBDYW5kaWRhdGVzCgojIFBhbGluZHJvbWUgIOKGkCDijZwowrDii5V84oqC4p-c4oeMKQojIFBhbGluZHJvbWVzIOKGkCDiiaFQYWxpbmRyb21lIENhbmRpZGF0ZXMKIyBGYWN0b3JzIOKGkCAoCiMg4pehKOKLhUNhbmRpZGF0ZXMpCiMg4pehw7cKIyDil6Eow5fiioMoCiMg4oqZ4ouF4ouF4oiYCiMgOgojIOKJpQojIHwg4oqZ4ouF4ouF4ouF4oiYCiMgOgojIOKJpAojICkpCiMg4oqDKOKWvXzilr3iipnil4wpCiMgKD3ijIouKS4KIyDiioMo4pa9fOKWveKKmeKXjCkKIyDil7TiiaEo4o2G4oqCKQojICkKCiMgMTAwIDk5OQojIDkwNjYwOQojIEZhY3RvcnMKCiMgQ2FuZGlkYXRlcyAxIDkKClBhbGluZHJvbWVzIDEwMDAgOTk5OQoKIyBJc1BhbGluZHJvbWUKCiMg4o2aRmFjdG9ycwojIAojIC_il4fiioLiirjijZooPjDip7spCiMg4pa9CiMg4omhKOKKguKKguKXocOXIMKw4oqCKcKw4pah4oqjCiMg4oqZ4ouF4ouF4ouFICMgVE9ETzogZml4CiMgCg==
