Grid  ← $ camdcimgtc
        $ jcfblpepre
        $ clojurermr
        $ aodcdefghu
        $ ajdcdefghj
        $ audcdefgho
        $ erujolcghl
        $ aedcdefghc
Words ← {"clojure"}

Parse     ← ⊜∘≠@\n.
Location  ← +1⊟⊃⊢⊣?
Locations ← ⊜Location:°⊡

Parse Grid
♭₂Locations⦷"clojure"
# ⇌♭₂Locations⦷⇌"clojure"
# ♭₂Locations⦷⍉¤"clojure"
# ⇌♭₂Locations⦷⍉¤⇌"clojure"

# ⦷ ⬚@\W⤸0_0"aeg"
# ⦷ ⍉⇌⬚@\W⤸0_0"aeg"
# ⦷ ⍉⇌⍉⇌⬚@\W⤸0_0"aeg"
# ⦷ ⍉⇌⍉⇌⍉⇌⬚@\W⤸0_0"aeg"
