┌─╴Rational
  # Create a new rational number
  # Rational ? Numerator Denominator
  New ← |2 ⊙⋅(⍤ "Please implement New" 0)
  
  # Rational ? Left Right
  Add ← |2 ⊙⋅(⍤ "Please implement Add" 0)
  
  # Rational ? Left Right
  Sub ← |2 ⊙⋅(⍤ "Please implement Sub" 0)
  
  # Rational ? Left Right
  Mul ← |2 ⊙⋅(⍤ "Please implement Mul" 0)
  
  # Rational ? Left Right
  Div ← |2 ⊙⋅(⍤ "Please implement Div" 0)
  
  # Value ? Rational
  Abs ← |1 ⊙(⍤"Please implement Abs" 0)
└─╴
