~ "resistor-color-duo.ua" ~ ResistorColorDuo

#Brown and black
⍤⤙≍ 10 ResistorColorDuo {"brown" "black"}

#Blue and grey
⍤⤙≍ 68 ResistorColorDuo {"blue" "grey"}

#Yellow and violet
⍤⤙≍ 47 ResistorColorDuo {"yellow" "violet"}

#White and red
⍤⤙≍ 92 ResistorColorDuo {"white" "red"}

#Orange and orange
⍤⤙≍ 33 ResistorColorDuo {"orange" "orange"}

#Ignore additional colors
⍤⤙≍ 51 ResistorColorDuo {"green" "brown" "orange"}

#Black and brown, one-digit
⍤⤙≍ 1 ResistorColorDuo  {"black" "brown"}
