# This workflow will verify the exercises in the repository.
#
# Requires scripts:
# - bin/verify-exercises

name: Test

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  verify_exercises:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Install uiua
        run: gh release download 0.13.0 --repo uiua-lang/uiua --dir /usr/local/bin --pattern uiua-bin-x86_64-unk
nown-linux-gnu-no-audio.zip

      - name: Verify all exercises
        run: bin/verify-exercises
